# Generated by Django 2.1.1 on 2018-11-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkdir', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='folder',
            field=models.CharField(max_length=128),
        ),
    ]
