# Generated by Django 2.1.1 on 2018-10-05 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0013_auto_20181005_1613'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
